server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Silvanoeng/sistemaCaixasEletronicos
          #username:
          #password:
          default-label: main
          search-paths:
            - 'configServer*'
          timeout: 5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

